[workspace]
members = ["cpu", "assembler", "isa", "logger", "args", "wasm-wrapper"]
resolver = "3"

[workspace.dependencies]
isa = { path = "isa" }
thiserror = "2.0.16"
logger = { path = "logger" }
args = { path = "args" }
