[package]
name = "vm"
version = "0.2.1"
edition = "2024"

[dependencies]
isa = { workspace = true }
thiserror = { workspace = true }
logger = { workspace = true }
args = { workspace = true }
num-traits = "0.2.19"
